### ISSUE TITLE
issue with release channel and corectl command

### ISSUE THREAD

**Issue by abhiesa** [TheNewNormal/coreos-osx#38] opened 2016-02-14 19:25 UTC
Hi team, every time, i try to go and set release channel to stable, it is resulting with alpha, with up command.

Also, with up command below issue is occurring. and execution stuck with Waiting for VM to be ready...

```sh
$ /Applications/CoreOS.app/Contents/Resources/up.command; exit;

Starting Docker Registry v2 on 192.168.64.1:5000 ...

Starting VM ...

> booting core-01
[corectl] alpha/955.0.0 already available on your system
[corectl] NFS started in order for '/Users/abhishek' to be made available to the VMs
Error: Unable to grab VM's IP after 30s (!)... Aborting

Usage:
  corectl load path/to/yourProfile [flags]

Examples:
  corectl load profiles/demo.toml

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'core-01' not found, or dead

Usage:
  corectl query [VMids] [flags]

Aliases:
  query, q

Flags:
  -a, --all    display extended information about a running CoreOS instance
  -i, --ip     displays given instance IP address
  -j, --json   outputs in JSON for easy 3rd party integration

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'core-01' not found, or dead

Usage:
  corectl query [VMids] [flags]

Aliases:
  query, q

Flags:
  -a, --all    display extended information about a running CoreOS instance
  -i, --ip     displays given instance IP address
  -j, --json   outputs in JSON for easy 3rd party integration

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Waiting for VM to be ready...
```

**Comment by rimusz** [comment] 2016-02-15 13:45
@abhiesa I'm trying to reproduce this one, but no luck, I always can switch between channels via:
```
Setup -> Change Release Channel
Halt/Up
or
Reload
```

**Comment by rimusz** [comment] 2016-02-15 13:55
oh, was able to reproduce it, will look deeper then

**Comment by rimusz** [comment] 2016-02-15 14:27
@abhiesa after bigger investigation it looks like the problem is only with `alpha` which is understandable as it is the `alpha` channel and it may not always function properly as expected

**Comment by AntonioMeireles** [comment] 2016-02-15 15:44
@abhiesa i was able to reproduce it just _once_ on alpha. working on figuring out what's going on...

**Comment by rimusz** [comment] 2016-02-23 09:23
closing in favour of https://github.com/TheNewNormal/corectl/issues/62

**Closed by rimusz** 2016-02-23 09:23 UTC

**Comment by abhiesa-tolexo** [comment] 2016-02-23 09:49
Both coreos-osx#38 and corectl#62, and the problem still persists. Please let one issue open, till it get fixed or released.
