### ISSUE TITLE
Docker build crash : A lot of no such file or directory

### ISSUE THREAD

**Issue by kvacquier** [TheNewNormal/coreos-osx#66] opened 2016-06-03 08:19 UTC
When I try to do a Docker build i have a lot of missing directories, during step one (need to do 
bash-4.2# mkdir /var/lib/docker/image/overlay/imagedb/
bash-4.2# mkdir /var/lib/docker/image/overlay/imagedb/content/
bash-4.2# mkdir /var/lib/docker/image/overlay/imagedb/content/sha256/
)
But then, during step 2 i have the following error : internal failure while setting the bit: open /var/lib/docker/network/files/local-kv.db: no such file or directory

**Comment by rimusz** [comment] 2016-06-03 11:06
@kvacquier which coreos channel you are using:
alpha
beta
stable

**Comment by kvacquier** [comment] 2016-06-03 11:32
I've tried with both alpha and stable

Le ven. 3 juin 2016 à 13:06, Rimas Mocevicius <notifications@github.com> a
écrit :

**Comment by rimusz** [comment] 2016-06-07 10:33
@kvacquier would you mind to try the latest v1.3.0, please.
But first delete the `~/coreos-osx/data.img` file before running the new version of the App

**Comment by rimusz** [comment] 2016-07-10 15:09
@kvacquier closing this one as I'm not able to reproduce your problem, plus I have released new v1.4.1 for the App, please try it.

**Closed by rimusz** 2016-07-10 15:09 UTC
